"""add_role_in_projects

Revision ID: 882bdf2bd842
Revises: ae1cca5d11b9
Create Date: 2025-11-28 16:29:14.052040

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '882bdf2bd842'
down_revision: Union[str, Sequence[str], None] = 'ae1cca5d11b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projectuserlink', sa.Column('project_role', sa.Enum('MANAGER', 'VIEWER', 'EDITOR', 'CREATOR', name='projectrole'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projectuserlink', 'project_role')
    # ### end Alembic commands ###
