services:
  fastapi-app:
    container_name: fastapi-app
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "${APP_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/newjira
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - postgres
    volumes:
      - .:/app
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=newjira
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: